-- migrate:up
INSERT INTO types (title)
VALUES
('Research Article'),
('Systematic Review'),
('Meta-Analysis'),
('Case Study'),
('Short Communication'),
('Letter'),
('Editorial'),
('Commentary'),
('Perspective'),
('Opinion'),
('Conference Paper'),
('Preprint'),
('Thesis'),
('Dissertation'),
('Study Protocol'),
('Erratum'),
('Correction'),
('Popular Science'),
('Explainer'),
('Tutorial'),
('How-To'),
('Guide'),
('Listicle'),
('Deep Dive'),
('Overview'),
('News'),
('Feature'),
('Report'),
('Interview'),
('Profile'),
('Investigation'),
('Column'),
('Op-Ed'),
('Essay'),
('Longread'),
('Photo Essay'),
('Book Review'),
('Critique'),
('Literary Analysis'),
('Annotation'),
('Summary'),
('Retelling'),
('Reading Notes'),
('Recommendation'),
('Comparison'),
('Author Profile'),
('Post'),
('Note'),
('Thought'),
('Story'),
('Thread'),
('Diary'),
('Rant'),
('Meme Post'),
('Whitepaper'),
('Documentation'),
('Changelog'),
('Release Notes'),
('Specification'),
('Benchmark'),
('Tech Review'),
('Case Report'),
('Postmortem'),
('Fiction'),
('Short Story'),
('Poem'),
('Novella'),
('Flash Fiction'),
('Fanfic'),
('Publicism'),
('Pamphlet'),
('Feuilleton'),
('Sketch'),
('Reportage'),
('Press Note'),
('Announcement'),
('Press Release'),
('Biographical Article'),
('Memoir'),
('Travelogue'),
('Culinary Article'),
('Product Review'),
('Comparative Review'),
('Ranking'),
('Top List'),
('FAQ'),
('Dictionary Entry'),
('Encyclopedia Article'),
('Educational Article'),
('Methodical Article'),
('Monograph'),
('Abstract'),
('Poster'),
('Demo'),
('Lecture'),
('Synopsis'),
('Coursework'),
('Research Report'),
('Analytical Note'),
('Forecast'),
('Chronicle'),
('Review of Events'),
('Agitational Article'),
('Sermon'),
('Treatise'),
('Manifesto'),
('Declaration'),
('Open Letter'),
('Marginalia'),
('Reading Diary'),
('Quote Collection'),
('Book Summary'),
('Digest');

-- migrate:down
DELETE FROM types WHERE id > 1;
ALTER SEQUENCE types_id_seq RESTART WITH 2;
