location / {
    try_files $uri $uri/ /index.php?$query_string;
}

location ~* \.(svg|png|jpe?g|gif|webp|avif|jxl|ico|tiff?|heic|css|js|mjs|map|webmanifest|wasm|json|jsonld|geojson|xml|txt|csv|pdf|eot|otf|ttf|ttc|woff2?|mp4|mov|webm|mpe?g|avi|ogv|mp3|wav|ogg|m4a|aac|mid|midi)$ {
    add_header Cache-Control "max-age=0, must-revalidate" always;
    try_files $uri =404;
}

location ~ \.php$ {
    fastcgi_pass $backend_ip:$backend_port;
    try_files    $fastcgi_script_name =404;
    include      fastcgi.conf;
    include      env/lore-bookforum.conf;
    # fastcgi_param  COUNTRY_CODE    $geoip2_data_country_code;
    # fastcgi_param  COUNTRY_NAME    $geoip2_data_country_name;
}