server {
    listen 80;
    server_name lore-bookforum.local lore.local;

    root /var/www/html/public;
    index index.php index.html;

    client_max_body_size 32m;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        try_files    $fastcgi_script_name =404;
        include      /etc/nginx/fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~* \.(svg|png|jpe?g|gif|webp|avif|jxl|ico|tiff?|heic|css|js|mjs|map|webmanifest|wasm|json|jsonld|geojson|xml|txt|csv|pdf|eot|otf|ttf|ttc|woff2?|mp4|mov|webm|mpe?g|avi|ogv|mp3|wav|ogg|m4a|aac|mid|midi)$ {
        add_header Cache-Control "max-age=0, must-revalidate" always;
        try_files $uri =404;
    }

    location ~ /\. {
        deny all;
    }
}